[Create] bagettt 모델링 생성
wecode-bootcamp-korea/27-1st-Bagettt-backend pull request #1
Opened 2021-11-30 09:22 UTC by jaemoon406

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [0] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-11-30 09:53 UTC, lordmyshepherd requested changes

2021-11-30 09:53 UTC, lordmyshepherd commented on packages/models.py
> +    tag            = models.ManyToManyField('Tag',related_name='packages')
한 줄 띄워주세요!
```suggestion
    tag            = models.ManyToManyField('Tag',related_name='packages')
    
```

2021-11-30 09:53 UTC, lordmyshepherd commented on packages/models.py
> +#         db_table = 'package_products'
주석은 뭔가요? 지워주세요!

2021-11-30 09:53 UTC, lordmyshepherd commented on packages/models.py
> +        db_table = 'orders'
이력 관리를 위해서 created_at, updated_at column을 추가해주세요!

2021-11-30 09:53 UTC, lordmyshepherd commented on packages/models.py
> +    user      = models.ForeignKey('User',on_delete=models.CASCADE)
이력 관리를 위해서 created_at, updated_at column을 추가해주세요!

2021-11-30 09:53 UTC, lordmyshepherd commented on packages/models.py
> +        db_table = 'package_images'
class명은 camelCase를 사용해 주세요!

```suggestion
class PackageImage(models.Model):
    image_url = models.CharField(max_length=2000)
    packages  = models.ForeignKey('Package')

    class Meta:
        db_table = 'package_images'
```

2021-11-30 09:53 UTC, lordmyshepherd commented on packages/models.py
> +    email    = models.CharField(max_length=200)
unique 옵션을 추가해주세요!

2021-11-30 10:02 UTC, jaemoon406 commented on packages/models.py
> +    user      = models.ForeignKey('User',on_delete=models.CASCADE)
추가했습니다.

2021-11-30 10:02 UTC, jaemoon406 commented on packages/models.py
> +        db_table = 'orders'
추가했습니다.

2021-11-30 10:04 UTC, jaemoon406 commented on packages/models.py
> +        db_table = 'package_images'
수정했습니다.

2021-11-30 10:06 UTC, jaemoon406 commented on packages/models.py
> +    email    = models.CharField(max_length=200)
추가했습니다.

2021-11-30 10:07 UTC, jaemoon406 commented on packages/models.py
> +    tag            = models.ManyToManyField('Tag',related_name='packages')
수정했습니다.

2021-11-30 14:30 UTC, jamessoun93 requested changes
추가리뷰 남겨드렸으니 반영해서 push 해주세요!
그리고 migration 파일이 하나도 없네요. 모델 작성 혹은 수정 시 꼭 migration 작업을 전부 완료한 뒤 migration 파일들을 함께 올려주셔야 팀원들과 공유가 됩니다 😉

2021-11-30 14:30 UTC, jamessoun93 commented on packages/models.py
> +# Create your models here.
불필요한 주석은 없애주세요!

2021-11-30 14:30 UTC, jamessoun93 commented on packages/models.py
> +    price          = models.CharField(max_length=50)
price 는 모델링 리뷰때 말씀드린대로 DecimalField 를 활용해서 소수점 두자리까지 허용해주세요.

2021-11-30 14:30 UTC, jamessoun93 commented on packages/models.py
> +    sales_volume   = models.IntegerField()
이런 정보는 최초 생성될 때 0을 넣어줄 수 있게 default=0 을 설정해주시는게 좋겠네요!

2021-11-30 14:30 UTC, jamessoun93 commented on packages/models.py
> +
M2M 필드를 사용하실때는 Foreign Key 와 구분을 위해 복수형으로 사용해주시면 가독성에 도움이 됩니다.
M2M 필드를 활용하여 원하는 정보를 가져오려고 할때 당연히 여러개의 객체를 QuerySet 리스트의 형태로 갖고오게 되니까요!

2021-11-30 14:30 UTC, jamessoun93 commented on packages/models.py
> +    user       = models.ForeignKey('User',on_delete=models.CASCADE)
이미 user 를 Order 에서 참조하고 있는데 여기에서 또 가지고 있을 필요가 있을까요?

2021-11-30 14:30 UTC, jamessoun93 commented on packages/models.py
> +    status       = models.CharField(max_length=50)
order status 는 모델링 리뷰때 말씀드린대로 정규화 해주셔야해요.
제가 이유가 뭐라고 그랬었죠?

2021-12-01 00:59 UTC, jaemoon406 commented on packages/models.py
> +    status       = models.CharField(max_length=50)
status 정규화 했습니다

2021-12-01 01:00 UTC, jaemoon406 commented on packages/models.py
> +    user       = models.ForeignKey('User',on_delete=models.CASCADE)
OrderItem 내 user 삭제했습니다.

2021-12-01 01:01 UTC, jaemoon406 commented on packages/models.py
> +
감사합니다! 복수로 변경했습니다.

2021-12-01 01:01 UTC, jaemoon406 commented on packages/models.py
> +    sales_volume   = models.IntegerField()
default추가했습니다.

2021-12-01 01:01 UTC, jaemoon406 commented on packages/models.py
> +# Create your models here.
삭제했습니다!

2021-12-01 01:36 UTC, jamessoun93 requested changes
리뷰 남겨드렸습니다.
모델 수정사항이 생길때는 꼭 migration 작업을 거치신 뒤 새로 생긴 migration 파일을 포함하여 push 해주셔야 팀원과 공유가 됩니다. 앞으로는 꼼꼼하게 확인해주세요 👍

2021-12-01 01:36 UTC, jamessoun93 commented on packages/models.py
> +    oerder = models.ForeignKey('Order',on_delete=models.CASCADE)
오타 확인해주세요.
- 이런 오타는 모델 수정 후 migration 과정 후 실제 데이터베이스에서 제대로 생성이 되었는지 확인해보셨으면 확인할 수 있었을텐데 지금 보니 migration 파일도 안올라와 있네요.
- 모델 변경사항이 있으면 무조건 migration 작업을 거친 후 변경사항이 데이터베이스에 제대로 반영되었는지 확인까지 마친 뒤 push 해주세요.

2021-12-01 01:36 UTC, jamessoun93 commented on packages/models.py
> +    description = models.CharField(max_length=100)
태그명이 아닌 description 만 존재하나요?

2021-12-01 01:36 UTC, jamessoun93 commented on packages/models.py
> +    sub_total    = models.IntegerField()
금액관련은 `DecimalField()` 사용하라고 가이드 드렸습니다!

2021-12-01 02:19 UTC, jaemoon406 commented on packages/models.py
> +    sub_total    = models.IntegerField()
DecimalField 사용했습니다

2021-12-01 02:19 UTC, jaemoon406 commented on packages/models.py
> +    description = models.CharField(max_length=100)
name 으로 수정했습니다.

2021-12-01 02:20 UTC, jaemoon406 commented on packages/models.py
> +    oerder = models.ForeignKey('Order',on_delete=models.CASCADE)
MySQL , migration 파일 생성 확인했습니다.

2021-12-01 06:42 UTC, merged