[CREATE] SignUpview
wecode-bootcamp-korea/27-1st-Bagettt-backend pull request #4
Opened 2021-12-03 02:36 UTC by jaemoon406

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-12-03 06:49 UTC, jamessoun93 commented
PR Template 관련해서 가이드 드린대로 수정해주세요~

2021-12-03 10:03 UTC, jamessoun93 requested changes

2021-12-03 10:03 UTC, jamessoun93 commented on users/urls.py
> +    # path('/signin',SigninView.as_view()),
불필요한 주석 없애주시고 나중에 실제로 SignIn 기능 추가하실때 추가해주세요!

2021-12-03 10:03 UTC, jamessoun93 commented on users/views.py
> +            print(password_regex_match(password))
print!?!?!?

2021-12-03 10:03 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({'message':'EMAIL_ALREADY_EXISTS'}, status = 401)
`401` 은 `UNAUTHORIZED` 의 의미를 갖는 HTTP status code 입니다. 
해당 요청은 인증요청을 하는게 아니고 SignUp 요청인데다가 여기에서는 존재하는 `email` 인지 확인하는 로직이라 이 부분에 알맞는 status code 를 찾아 리턴해주세요!

2021-12-03 10:08 UTC, bigfanoftim requested changes

2021-12-03 10:08 UTC, bigfanoftim commented on users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode()
`decode()`라고 작성하신건 의도하신걸까요?

2021-12-03 11:52 UTC, jaemoon406 commented on users/views.py
> +            print(password_regex_match(password))
아.. debuging 하던게 남았네요 삭제 하겠습니다

2021-12-03 11:55 UTC, jaemoon406 commented on users/urls.py
> +    # path('/signin',SigninView.as_view()),
넵

2021-12-03 11:57 UTC, jaemoon406 commented on users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode()
'utf-8'

2021-12-03 11:57 UTC, jaemoon406 commented on users/views.py
> +                return JsonResponse({'message':'EMAIL_ALREADY_EXISTS'}, status = 401)
400으로 변경했습니다.

2021-12-05 09:49 UTC, jamessoun93 approved these changes
LGTM
- PR 라벨을 `리뷰요청`으로 변경해주셔야 빠른 확인이 가능하니 수정 완료하시면 꼭 라벨 변경 부탁드립니다.

2021-12-05 09:49 UTC, merged